### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by bjoerns1983** [bjoerns1983/Emby.Plugin.TelegramNotification#2]
- [x] Move to netstandard2.0 and Emby Core 4.0.0.2
- [x] Add Logo
- [x] Rework config.html
- [x] Compability with Playback Reporting 
- [ ] ~~Check if it is possible to include pictures (not supported by Emby atm)~~
- [x] Add descriptions
- [x] Better Readme regarding setup
- [ ] Automatic retrieve of Chat_ID
- [x] Clean up code

**Comment by Akior** [comment]
Hello there!

Check if it is possible to include pictures (not supported by Emby atm)

There are possible to send via sendPhoto api with photo url.
Emby it show without auth like
http://server_url/emby/Items/Item.Id/Images/Primary 
So if you can bind on http port  and get movie\show ID you can provide image to telegram.
Great if plugin will have new cusom field [server url]

**Comment by bjoerns1983** [comment]
PR welcome if you like.
I have already checked it and the Emby notification framework does not support it.
Thats means the complete Plugin need to be rewritten and regulary updated to pull the data by itself.
I wont put that much affort in a plugin for a closed source product.

Maybe the new Webhooks are a solution.

**Comment by albertparis** [comment]
Radarr and Sonarr send an IMDB link with the notification, then normally telegram fetches the image from it

**Comment by bjoerns1983** [comment]
But Emby does not provide this information to the plugin. So that would mean everything must be rewritten so the plugin actually communicates with Emby's database which is out of the scope of this plugin.

**Comment by fandangos** [comment]
> Radarr and Sonarr send an IMDB link with the notification, then normally telegram fetches the image from it

I have sonarr and radarr sending me notifications over telegram but there's no image, just a simple text. 

How do you get images from those 2?

**Comment by bjoerns1983** [comment]
This Plugin does not support images.
